### ISSUE TITLE
OAuth2.0 Vagrant up broken

### ISSUE THREAD

**Issue by SteveWooding** [udacity/fsnd-issues#1]
This is the same issue that was in the main Vagrant provisioning script (i.e. apt-get upgrade fails waiting for user input).

I have already created a pull request to fix this issue. It just needs to be merged in (after being double checked of course). Here's the link for the PR: https://github.com/udacity/OAuth2.0/pull/10

**Comment by forbiddenvoid** [comment]
Merged.
