### ISSUE TITLE
Bug in RWDF_L2_Solution.zip CSS code

### ISSUE THREAD

**Issue by SteveWooding** [udacity/fsnd-issues#10]
In the solution code given at the bottom of [this page](https://classroom.udacity.com/nanodegrees/nd004/parts/fe2ad0cf-06b0-4541-87ab-0b6d59e21ef1/modules/afa5ca8b-f8dc-4160-83ff-3e5ccc2e1972/lessons/94d40e3d-d0b8-4c04-bc92-036759492d28/concepts/35201693450923) contents the following CSS:

```
.top-news__item a {
  text-decoration: none;
  color: #666;
  padding: 1.5em inherit;
}
```

The issue is with the `padding` property: you can not specify `inherit` within a shorthand CSS property, as discussed [here](https://developer.mozilla.org/en-US/docs/Web/CSS/Shorthand_properties). So the longhand properties need to be used. Here is a proposed answer:

```
.top-news__item a {
  text-decoration: none;
  color: #666;
  padding-top: 1.5em;
  padding-bottom: 1.5em;
  padding-left: inherit;
  padding-right: inherit;
}
```

**Comment by forbiddenvoid** [comment]
Fixed.
