### ISSUE TITLE
Git Tagging Possible Quiz Question Error

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fsnd-issues#100]
https://classroom.udacity.com/nanodegrees/nd004/parts/f05dd1a8-5cb0-44ce-b9e9-b30fc274bcdc/modules/6b870a4f-94d1-4e8b-986c-0ace411d63e7/lessons/61776182-df3f-4767-9558-5d1591c1a709/concepts/f22ea0e4-4a68-4d3a-91c8-0c19915af71f

The question asks whether the just-created tag will show up in Git log and the correct answer says it won't.

However, with git 2.15.0, tags show up in the git log output:

$ git --version 
git version 2.15.0.windows.1

$ git log --oneline 
7e1cd04 (HEAD -> master, tag: v1.0) Ignore project.docx file 
cfaf68d Add header to blog 
7c11dc0 Initial commit

Ticket #637617

**Comment by forbiddenvoid** [comment]
Removed the quiz since this change effectively negates using git log on its own.
