### ISSUE TITLE
Google auth heroku app not working

### ISSUE THREAD

**Issue by zach-col** [udacity/fsnd-issues#101]
Instructor notes include link to heroku app
http://udacity-oauth.herokuapp.com/

but is returning application error

https://classroom.udacity.com/nanodegrees/nd004/parts/8d3e23e1-9ab6-47eb-b4f3-d5dc7ef27bf0/modules/348776022975461/lessons/3960758610/concepts/39804189000923

**Comment by karlud** [comment]
Thank you! I've removed the link.
