### ISSUE TITLE
SoundCloud no longer accepting API signups

### ISSUE THREAD

**Issue by SteveWooding** [udacity/fsnd-issues#102]
[This page](https://classroom.udacity.com/nanodegrees/nd004/parts/8d3e23e1-9ab6-47eb-b4f3-d5dc7ef27bf0/modules/47a1ea0f-75ff-4654-9c90-89cf02246783/lessons/4628431284/concepts/52474372940923) from the API course talks about using the SoundCloud API. However, SoundCloud has stopped signups for developer accounts at the moment due to high demand. A note regarding this issue could be added to the page.

**Comment by karlud** [comment]
Good catch. I'll add a note.
