### ISSUE TITLE
Missing lesson files

### ISSUE THREAD

**Issue by zach-col** [udacity/fsnd-issues#104]
https://classroom.udacity.com/nanodegrees/nd004/parts/8d3e23e1-9ab6-47eb-b4f3-d5dc7ef27bf0/modules/47a1ea0f-75ff-4654-9c90-89cf02246783/lessons/4592928861/concepts/52457425860923

Lesson above is missing file lessons in instructor notes.

Possibly also put a not of the curl command used in video?

**Comment by forbiddenvoid** [comment]
Fixed
