### ISSUE TITLE
lesson code and solution code have different paths

### ISSUE THREAD

**Issue by zach-col** [udacity/fsnd-issues#105]
Lesson
https://classroom.udacity.com/nanodegrees/nd004/parts/8d3e23e1-9ab6-47eb-b4f3-d5dc7ef27bf0/modules/47a1ea0f-75ff-4654-9c90-89cf02246783/lessons/4592928861/concepts/52457425870923

has the path @app.route('/protected_resource')

while the solution code has @app.route('/api/resource')

**Comment by forbiddenvoid** [comment]
Hi! You might notice that right at the beginning of the video, Lorenzo replaces the `api/resource` path with `/protected_resource`, this is only meant to demonstrate the different between open resources and protected resources. Either route path is fine to use.
