### ISSUE TITLE
Using Cookies in Python adding clarification

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fsnd-issues#108]
https://classroom.udacity.com/nanodegrees/nd004/parts/f05dd1a8-5cb0-44ce-b9e9-b30fc274bcdc/modules/b08bb93f-d13e-42d6-a60c-8c7d4d263c42/lessons/773150bb-8e88-4457-b077-3b8a02018f33/concepts/896086f7-1646-4fab-a3c6-36b8e70b091d#

I have a suggestion for Lesson 13, lecture 4, 'Using Cookies in Python' section.

I sent a question to my mentor Trish who gave me the following explanation. I think it'll be really helpful if this gets added to the lecture since this specific explanation is missing in the original lecture. It took me a long time to figure out, hoping others won't have to.

My question was related to a method that was not explained:

in_cookie = SimpleCookie(self.headers["Cookie"]) in_data = in_cookie["bearname"].value

Where is the '.value' coming from? I tried printing headers, and cookies.SimpleCookie(self.headers['cookie']). It prints out all the cookies set by post request.

Here's Trish's answer regarding Morsel instances which has not been mentioned in the lecture:

A SimpleCookie() is derived from a BaseCookie() and a BaseCookie() is defined as "dictionary-like object whose keys are strings and whose values are Morsel instances" [1]. So the keys of the SimpleCookie() are strings and the values are Morsel instances.

These Morsel instances are also a dictionary-like object with a defined set of keys (expires, path, domain, max-age, etc). The value of each Morsel can be obtained using Morsel.value.

[1] https://docs.python.org/2/library/cookie.html

Another way to think about this is that SimpleCookie is a dictionary with key "bearname" and values that are Morsel instances, each of which have a key and value.

In the Python interpreter you can try a few things.

>>> from http.cookies import SimpleCookie, CookieError 
>>> 
>>> out_cookie = SimpleCookie() 
>>> out_cookie["bearname"] = "Smokey Bear" 
>>> out_cookie["bearname"]["max-age"] = 600 
>>> out_cookie["bearname"]["httponly"] = True 
>>> 
>>> for k,v in out_cookie.iteritems(): 
... print "Key: ", k, "\nValue: ", v, type(v) 
... for k1, v1 in v.iteritems(): 
... print "Morsel Key: ", k1, "Value: ", v1 
... 
Key: bearname 
Value: Set-Cookie: bearname="Smokey Bear"; httponly; Max-Age=600 <class 'Cookie.Morsel'> 
Morsel Key: comment Value: 
Morsel Key: domain Value: 
Morsel Key: secure Value: 
Morsel Key: expires Value: 
Morsel Key: max-age Value: 600 
Morsel Key: version Value: 
Morsel Key: path Value: 
Morsel Key: httponly Value: True

Ticket #650684

**Comment by forbiddenvoid** [comment]
Hey @karlud: Do you want to add a link to the docs for the Cookie modules here? I'm not sure we need a long explanation,  but if people want to research more, they should be able to.

**Comment by karlud** [comment]
Yeah, good point. Adding!
