### ISSUE TITLE
gdisconnect(): Use dictionary get() method instead of []

### ISSUE THREAD

**Issue by SteveWooding** [udacity/fsnd-issues#11]
In [this file](https://github.com/udacity/ud330/blob/master/Lesson2/step6/project.py) in the `gdisconnect()` function, the access token is accessed directly, which can raise a KeyError if not logged in. Should use the `get()` method instead.

I've submitted a pull request to fix this issue (plus removing some tab characters): https://github.com/udacity/ud330/pull/47

**Comment by karlud** [comment]
Merged. Thank you!
