### ISSUE TITLE
Add note that link to file to download is at bottom of the page

### ISSUE THREAD

**Issue by SteveWooding** [udacity/fsnd-issues#111]
In the Git setup lessons, the link to the `udacity-terminal-config.zip` can easily be missed as the instructions do not tell the student where the link is located.

Here are links to the affected pages:

https://classroom.udacity.com/nanodegrees/nd004/parts/f05dd1a8-5cb0-44ce-b9e9-b30fc274bcdc/modules/6b870a4f-94d1-4e8b-986c-0ace411d63e7/lessons/1b369991-f1ca-4d6a-ba8f-e8318d76322f/concepts/63a6f935-dea7-43c2-aaa3-61deea5070c8

https://classroom.udacity.com/nanodegrees/nd004/parts/f05dd1a8-5cb0-44ce-b9e9-b30fc274bcdc/modules/6b870a4f-94d1-4e8b-986c-0ace411d63e7/lessons/1b369991-f1ca-4d6a-ba8f-e8318d76322f/concepts/8a5af628-7a18-49cf-bbc8-02691762f862

A note could be added (or better still a hyperlink) to help students find the link.

**Comment by forbiddenvoid** [comment]
For the sake of consistency, we intentionally omit specific references to page locations for links. The reason for this is that it's possible that our design may change in the future and that the location may change. We'd have to go back, find and change all of those references.
