### ISSUE TITLE
Clerical error on Lesson 17 - Video 3

### ISSUE THREAD

**Issue by mkhoury93** [udacity/fsnd-issues#113]

**Comment by mkhoury93** [comment]
This isn’t a question, but rather a report on a clerical error.
In the video, Lorenzo says that the @app.route is: (’/users’) . However, from the GitHub, it has been corrected to @app.route(’/api/users’). It would be good to modify the HTML content on the bottom of the page in the video to let users know and not spend a huge amount of time debugging the 404 URL not found!

**Comment by karlud** [comment]
Thanks for reporting this. Could you provide a link to the page? "Lesson 17 - Video 3" does not seem to refer to a page that has @app.route in it, so I'm guessing I'm looking at a different page than you are.

**Comment by forbiddenvoid** [comment]
Closing for lack of response. Please re-open if this is still an issue.
