### ISSUE TITLE
2. Quiz: Is it a palindrome?

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fsnd-issues#114]
https://classroom.udacity.com/nanodegrees/nd004/parts/a98f5fbf-0b2a-457d-8f06-7025979cf2bc/modules/38770727-af7f-4886-999f-4e26eea93794/lessons/5190620443/concepts/52540186220923#

There's a mistake in the solution provided by Philip around 3.36 mark in the video. 
str.strip() function won't remove all the spaces from the string, only leading and trailing spaces. 
str.replace(' ', '') could be used instead to get the job done.

Ticket #684664

**Comment by karlud** [comment]
I've added a note that the candidate in this video might not be giving a 100% correct answer. Thank you for pointing this out — as presented, it is plenty confusing!
