### ISSUE TITLE
ud197 Developer Tools

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fsnd-issues#115]
https://classroom.udacity.com/courses/ud197/lessons/3423258756/concepts/14c72fe3-e3fe-4959-9c4b-467cf5b7c3a0 

"What we written it is the virtualbox only support vagrant and command vagrant up will download and install it to virtualbox 
but now this no longer true after my long search in internet now vagrant support virtualbox and vmware also 
the command vagrant up don't work on my machine because i have vmware and virtualbox installed so the true command will be vagrant up --provider virtual_program 
like vagrant up --provider virtualbox 
or vagrant up --provider vmware 
vargrant up woks but on machines that only have one virtual program"

Ticket #693703

**Comment by karlud** [comment]
From what I can tell, VMWare for Vagrant is a commercial product that we do not provide or support: https://www.vagrantup.com/docs/vmware/installation.html

**Comment by JessicaBettencourt** [comment]
Thanks for the clarification!
