### ISSUE TITLE
Linux Server Project Instructions

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fsnd-issues#116]
I've had several students write in asking if a different service can be used other than AWS for this project. Maybe we can clarify this in the instructions?

**Comment by karlud** [comment]
It's already there:

"We're recommending Amazon Lightsail for this project. If you prefer, you can use any other service that gives you a publicly accessible Ubuntu Linux server. But Lightsail works pretty well and it's what we've tested."

https://classroom.udacity.com/nanodegrees/nd004/parts/ab002e9a-b26c-43a4-8460-dc4c4b11c379/modules/357367901175462/lessons/3573679011239847/concepts/c4cbd3f2-9adb-45d4-8eaf-b5fc89cc606e?contentVersion=4.0.0&contentLocale=en-us
