### ISSUE TITLE
Vagrant download boxes issue

### ISSUE THREAD

**Issue by SteveWooding** [udacity/fsnd-issues#117]
Vagrant has moved the box images to a different domain and have now removed redirects. This means until Vagrant 2.0.3 is out, the downloading of all boxes will fail.

A workaround is to change the server URL in the `Vagrantfile` by adding this line:

```
Vagrant::DEFAULT_SERVER_URL.replace('https://vagrantcloud.com')
```

near the top (just after the `Vagrant.configure(2) do |config|` seems senible.

This should be done as soon as possible to prevent students getting frustrated.

More details on this issue can be found here: https://github.com/hashicorp/vagrant/issues/9442

**Comment by forbiddenvoid** [comment]
I updated the Vagrantfile. It seems to work for me. @SteveWooding can you verify that this works now for you?
