### ISSUE TITLE
Dead link in Review your Skills in the Logs Analysis project

### ISSUE THREAD

**Issue by KalindiFonda** [udacity/fsnd-issues#118]
https://classroom.udacity.com/nanodegrees/nd004/parts/8d3e23e1-9ab6-47eb-b4f3-d5dc7ef27bf0/modules/bc51d967-cb21-46f4-90ea-caf73439dc59/lessons/262a84d7-86dc-487d-98f9-648aa7ca5a0f/concepts/d7166abe-4fa4-4af3-9a33-77729cdcff9a The first link "Joining Tables" is dead.

**Comment by forbiddenvoid** [comment]
Deleted dead link.
