### ISSUE TITLE
“Securing your API”: passlib 1.7 changes

### ISSUE THREAD

**Issue by Zinston** [udacity/fsnd-issues#119]
In "Adding Users and Logins" (FSND Part 3 Lesson 17: "Securing your API"), the code used to hash a password is `pwd_context.encrypt(password)`.
However, as I tried to do this on my one later with one of the quizzes, I went into passlib's documentation and found this:

> Changed in 1.7:
Prior releases used `PasswordHash.encrypt()` for hashing, which has now been renamed to `PasswordHash.hash()`. A compatibility alias is present in 1.7, but will be removed in Passlib 2.0.

So right now it still works but it won't for long and if you look into the documentation for how to encrypt, you're not going to find `.encrypt()` which is somewhat confusing when you're trying to do the assignments. `pwd_context.encrypt(password)` can safely be replaced with `pwd_context.hash(password)`.

Maybe adding a note underneath the lesson would help future students?

**Comment by forbiddenvoid** [comment]
Done.
