### ISSUE TITLE
Forum Moderator pull requests are being ignored

### ISSUE THREAD

**Issue by Aqueum** [udacity/fsnd-issues#12]
Students are wasting hours/days battling with bug-ridden "Solution Code" in "3 The Backend: Databases & Applications".  Forum Moderators (Steve Wooding for example) have 2 and 3 month old pull requests that are still apparently being ignored.  This can't happen in a course where students are paying significant sums monthly.

**Comment by asparr** [comment]
@aqueum it depends on the repo, in some cases the original instructor is no longer at Udacity, and we don't have access to the repo used in the course. Generally, Steve's pull requests are reviewed by our Instructors who Steve has access to.

**Comment by Aqueum** [comment]
@asparr, you guys are the experts, but I'd have thought you could fork repos like that, fix the bugs in the fork then change your links to point to your fork.

**Comment by karlud** [comment]
This is in progress! Thanks as always to Steve for his tireless work to improve the student experience with this code.
