### ISSUE TITLE
Module missing in Part 3 between Lesson 7 and Lesson 8

### ISSUE THREAD

**Issue by wangela** [udacity/fsnd-issues#120]
Lesson 7 ends with CRUD of Restaurant names, and Lesson 8 begins (using Flask) with reading from restaurantmenu.db and expecting Menu Items to be populated (but they haven't been, only restaurant names). David agrees there's a step missing.

**Comment by wangela** [comment]
Any plans to fix this? I'm looking to make progress in this course this week and have been waiting for the content to be provided.

**Comment by forbiddenvoid** [comment]
Hi there! I went back through this, and it looks like what I thought was a missing step was just covered earlier in the course. In Lesson 6 (working with CRUD), Lorenzo provided a Python file called 'lots_of_menus.py' that can be used to populate the database with Menu Items.

The link to that script is here: https://github.com/udacity/Full-Stack-Foundations/blob/master/Lesson_1/lotsofmenus.py
