### ISSUE TITLE
Goolge OAuth login not working on some Lightsail servers

### ISSUE THREAD

**Issue by SteveWooding** [udacity/fsnd-issues#121]
## Background

Google OAuth login now does not work with IP addresses. This is an issue for the Linux Server Configuration project. The error you receive is:

> Error: invalid_request
>
> Permission denied to generate login hint for target domain.

The general solution is to use the domain name that Lightsail assigns each server. This is not documented anywhere reliably, so the best way of determining it is to use the `nslookup` command or an online reverse DNS service, such as https://remote.12dt.com.

> Side note: Only servers in the Virginia region will have the the domain name in the format `ec2-10-20-30-40.compute-1.amazonaws.com`. If the server is in another region, such as London, the format is `ec2-10-20-30-40.eu-west-2.compute.amazonaws.com`. That is why it is best to use a reverse DNS lookup to get the correct domain name. The Lightsail notes could clarify how to determine the domain name.

This domain name should then be used in the "Authorized JavaScript origins" setting instead of the IP address.

## Issue with some Lightsail servers

However, some Lightsail server domain names don't seem to be recognized by Google, and the error produced when an IP address is persistent. I suppose this might be a DNS configuration issue in one or more of the AWS regions. More testing of Lightsail servers in different regions would need to be carried out to confirm this hypothesis.

## Workaround solution

I discovered that if a wildcard DNS service was used, Google accepted it as the domain where the login button was being served. I used the service at http://xip.io. The domain name is formed by prepending the IP address. For example, http://35.178.50.38.xip.io for the IP address `35.178.50.38`.

**Comment by karlud** [comment]
I'm going to add a note about this to the project instructions. Thanks!

**Comment by karlud** [comment]
Added.
