### ISSUE TITLE
Drawing Square Turtles Forum Post Closed

### ISSUE THREAD

**Issue by kellim** [udacity/fsnd-issues#123]
This came up for a student I was working with -
 this page https://classroom.udacity.com/nanodegrees/nd004/parts/fe2ad0cf-06b0-4541-87ab-0b6d59e21ef1/modules/356120945175460/lessons/1004409226/concepts/9944900980923# has a link that says Drawing Square Turtles - Use this discussion thread to post your response. that is linked to http://discussions.udacity.com/t/drawing-square-turtles-f/16124 but that forum topic is closed and you can't post to it.

**Comment by forbiddenvoid** [comment]
We're working on an alternate solution for these forum posts.
