### ISSUE TITLE
Filename in video does not match one in respoitory

### ISSUE THREAD

**Issue by SteveWooding** [udacity/fsnd-issues#13]
The file name in the video on [this page](https://classroom.udacity.com/nanodegrees/nd004/parts/8d3e23e1-9ab6-47eb-b4f3-d5dc7ef27bf0/modules/47a1ea0f-75ff-4654-9c90-89cf02246783/lessons/4592928861/concepts/52457425980923) (`veggie_tester.py`) does not match the one in the starter code, which is called `seafood_tester.py`. This maybe confusing.

Since changing the video is harder, can we change the filename of the tester code?

**Comment by forbiddenvoid** [comment]
Done.
