### ISSUE TITLE
Error in Git Ignore quiz

### ISSUE THREAD

**Issue by SteveWooding** [udacity/fsnd-issues#14]
In the first quiz on [this page](https://classroom.udacity.com/nanodegrees/nd004/parts/f05dd1a8-5cb0-44ce-b9e9-b30fc274bcdc/modules/6b870a4f-94d1-4e8b-986c-0ace411d63e7/lessons/5f584ce7-1b7b-4848-80c1-b559739ea363/concepts/d4275710-06eb-431c-bec6-13a202f1dfbb), the answer of "LONDFILE.PNG" is marked as correct.

However, an entry of `*.png` in the `.gitignore` file would not ignore this file, due to the upper case `PNG` extension. So this quiz needs to be altered in somewhere to make it correct.

**Comment by SteveWooding** [comment]
Case sensitivity depends on the `core.ignorecase` configuration though (as pointed out [here](https://discussions.udacity.com/t/lesson-5-6-having-git-ignore-files/309274/4) on the forums). Though this setting is `false` by default.

**Comment by forbiddenvoid** [comment]
Fixed.
