### ISSUE TITLE
Reference to missing quiz

### ISSUE THREAD

**Issue by SteveWooding** [udacity/fsnd-issues#15]
In the Floats lesson, page 3, [Many Floats](https://classroom.udacity.com/nanodegrees/nd004/parts/fe2ad0cf-06b0-4541-87ab-0b6d59e21ef1/modules/31cc93f7-9d62-44d2-b0fc-ab68b4ff90f0/lessons/171900e0-d0ab-465b-b747-402a3adcffc5/concepts/ddba8559-6bcc-4729-bea6-28c461a8f3c2), reference is made to a previous quiz (just before last code example). What quiz is being referred to here? If it exists within the FSND, a link to it would be useful.

**Comment by forbiddenvoid** [comment]
Good catch. This is referring to the previous example, not a quiz.
