### ISSUE TITLE
Device Emulation quiz - DPR issue

### ISSUE THREAD

**Issue by SteveWooding** [udacity/fsnd-issues#16]
The quiz on [this page](https://classroom.udacity.com/nanodegrees/nd004/parts/fe2ad0cf-06b0-4541-87ab-0b6d59e21ef1/modules/afa5ca8b-f8dc-4160-83ff-3e5ccc2e1972/lessons/3ecd9f0c-a731-4a38-95b9-95a95febf7b2/concepts/35247994450923) has been causing issues for some students for some time now. I think I have finally got to the bottom of why some students can never complete the quiz.

It seems that on some devices, the DPR does not equal 3.5, but something very close. I got a student to run this at the console:

```
window.devicePixelRatio
```

and they got a value of 3.4999999... Close, but it fails the test all the same. Not sure why this is happening (maybe a bug in Chrome), but a suitable work around would be to relax the requirement for this last test.

**Comment by forbiddenvoid** [comment]
Unfortunately this can't be fixed. The tests for the Chrome extension don't have an option for approximations or ranges.

**Comment by SteveWooding** [comment]
OK, that is a shame. However, maybe a note needs to be added for students who experience this issue?
