### ISSUE TITLE
Missing link in Q3 of Logs Analysis Project

### ISSUE THREAD

**Issue by SteveWooding** [udacity/fsnd-issues#17]
In the description of question 3 ([on this page](https://classroom.udacity.com/nanodegrees/nd004/parts/8d3e23e1-9ab6-47eb-b4f3-d5dc7ef27bf0/modules/bc51d967-cb21-46f4-90ea-caf73439dc59/lessons/262a84d7-86dc-487d-98f9-648aa7ca5a0f/concepts/b1bc900a-44ea-43e9-a51b-d3313705277f)) refers back to a previous lesson, but there is no link here back to it.

**Comment by karlud** [comment]
Fixed! Thank you.
