### ISSUE TITLE
Dead link on REST Constraints page

### ISSUE THREAD

**Issue by SteveWooding** [udacity/fsnd-issues#18]
The second link on [this page](https://classroom.udacity.com/nanodegrees/nd004/parts/8d3e23e1-9ab6-47eb-b4f3-d5dc7ef27bf0/modules/47a1ea0f-75ff-4654-9c90-89cf02246783/lessons/4594018829/concepts/52981798390923#) is now dead.

It is available, however, on the Wayback Machine [here](https://web.archive.org/web/20151218043450/http://imasters.expert/rest-architecture-model-definition-constraints-benefits/).

Or find an alternative live REST article.

**Comment by karlud** [comment]
Removed dead link.
