### ISSUE TITLE
Old link to AWS Development Environment

### ISSUE THREAD

**Issue by SteveWooding** [udacity/fsnd-issues#19]
On [this page](https://classroom.udacity.com/nanodegrees/nd004/parts/ab002e9a-b26c-43a4-8460-dc4c4b11c379/modules/357367901175461/lessons/4331066009/concepts/48010894640923) of the Linux Security lesson, there is an old link to the now obsolute AWS development environment.

Probably best just to delete this link. Thanks!

**Comment by karlud** [comment]
Good catch. Removed!
