### ISSUE TITLE
Clearer instructions for rate limiting exercise

### ISSUE THREAD

**Issue by SteveWooding** [udacity/fsnd-issues#2]
For the rate limiting quiz [here](https://classroom.udacity.com/nanodegrees/nd004/parts/8d3e23e1-9ab6-47eb-b4f3-d5dc7ef27bf0/modules/47a1ea0f-75ff-4654-9c90-89cf02246783/lessons/4592928861/concepts/52457426030923), clearer, written instructions might be useful. Students seem to gloss over the long 3 minute video on the previous page and not get the Redis server running.

Something along the lines to my answer [here](https://discussions.udacity.com/t/rate-limiting-exercise-getting-errors-while-running-the-code/262880/2) would be a good basis.

**Comment by forbiddenvoid** [comment]
Hey Steve. I've added your instructions to the classroom. Thanks!
