### ISSUE TITLE
Idea: Display something other than 'Hello World' message

### ISSUE THREAD

**Issue by SteveWooding** [udacity/fsnd-issues#20]
On the page [Your First WSGI Application](https://classroom.udacity.com/nanodegrees/nd004/parts/ab002e9a-b26c-43a4-8460-dc4c4b11c379/modules/357367901175461/lessons/4340119836/concepts/48018692630923), maybe have the simple WSGI display something other than the message 'Hello World!', to distinguish it from the 'Hello world' message on the Apache page.

This is from feedback from a student who got confused as to whether the WSGI was working.  So maybe a message such as "Welcome to your fist WSGI app!" would be better.

Thanks!

**Comment by forbiddenvoid** [comment]
Updated. Nice suggestion!
