### ISSUE TITLE
Idea: Add note about Apache warning when running on Vagrant VM

### ISSUE THREAD

**Issue by SteveWooding** [udacity/fsnd-issues#21]
It might be a good idea to reassure students that the warning message "Could not reliably determine the server's fully qualified domain name..." when restarting/starting apache is nothing to worry about. A student on a 1:1 said they thought is was an error.

This message could be put [on this page](https://classroom.udacity.com/nanodegrees/nd004/parts/ab002e9a-b26c-43a4-8460-dc4c4b11c379/modules/357367901175461/lessons/4340119836/concepts/48159388430923) where the instruction to restart Apache is located.

Thanks!

**Comment by karlud** [comment]
Done! Thanks for the suggestion.
