### ISSUE TITLE
Add note that udacity.com/catalog-api doesn't work

### ISSUE THREAD

**Issue by SteveWooding** [udacity/fsnd-issues#22]
In the video [on this page](https://classroom.udacity.com/nanodegrees/nd004/parts/8d3e23e1-9ab6-47eb-b4f3-d5dc7ef27bf0/modules/47a1ea0f-75ff-4654-9c90-89cf02246783/lessons/4594018830/concepts/52420831780923), it mentions the Udacity Catalog API. While the web address shown does not work, the API still does. 

Documentation for it is available in the form of a PDF document [here](https://s3.amazonaws.com/content.udacity-data.com/techdocs/UdacityCourseCatalogAPIDocumentation-v0.pdf), so this could be linked to on [this page](https://classroom.udacity.com/nanodegrees/nd004/parts/8d3e23e1-9ab6-47eb-b4f3-d5dc7ef27bf0/modules/47a1ea0f-75ff-4654-9c90-89cf02246783/lessons/4594018830/concepts/52420831780923) of the course.

**Comment by karlud** [comment]
Updated!
