### ISSUE TITLE
Cannot open project review links

### ISSUE THREAD

**Issue by jsoetens** [udacity/fsnd-issues#24]
I cannot open my project review (movie trailer website). The link by email and the button to review in the classroom don't work. They open in a browser but keep loading, I tried both Safari & Chrome (all on latest versions). Can you have a look please as I would like to read the review ;-) Thanks

**Comment by jsoetens** [comment]
I have now been able to see the project review.

**Comment by SteveWooding** [comment]
OK, that's great. I'm not sure what was happening there. I was just asking around about it. Glad it's working for you now.

**Comment by jsoetens** [comment]
Just about half an hour ago I couldn't open my Classroom at all, when it finally did it still didn't work. After changing course (NOT Resume Learning), I could go back to the Nanodegree part and all was smooth. Hope this is helpful. You can close the issue, thanks!

**Comment by SteveWooding** [comment]
Thanks for the explanation.

**Comment by SteveWooding** [comment]
Looks like I don't have permission to close it. A Udacity member of staff will close it later.

**Comment by jsoetens** [comment]
I already tried to close the issue myself but

**Comment by SteveWooding** [comment]
If you click the GitHub icon, that will open the issue up in GitHub, then you can close the issue from there.
