### ISSUE TITLE
Add link to Heroku Postgres installation page

### ISSUE THREAD

**Issue by SteveWooding** [udacity/fsnd-issues#3]
On [this page](https://www.udacity.com/wiki/ud330/deploy) about deploying an app to Heroku, in step 5, it might be a good idea to provide a link to the Heroku Postgres add-on installation page:

* https://elements.heroku.com/addons/heroku-postgresql

A student missed this part and got lost following the instructions on the page.

**Comment by forbiddenvoid** [comment]
@SteveWooding: Where is this wiki page linked from? We've been trying to eliminate these types of content, but I can seem to find a link in our content for it.

**Comment by SteveWooding** [comment]
I'm not sure either. A student just referenced it directly on the forums. I've asked the student where they got it from (if they indeed remember themselves).

**Comment by SteveWooding** [comment]
The student never answered by the way. I suppose another solution is to delete the wiki pages, if not required any more.
