### ISSUE TITLE
vagrant folder not mounted after installation

### ISSUE THREAD

**Issue by patilashvini888** [udacity/fsnd-issues#31]

**Comment by karlud** [comment]
Hello! I need a little more information about what you're seeing here. Can you describe what you did and what results you got?

**Comment by SteveWooding** [comment]
This issue should be resolved now for future students. To fix your installation however, make sure line 6 of the `Vagrantfile` is the same as given [here](https://github.com/udacity/fullstack-nanodegree-vm/blob/master/vagrant/Vagrantfile). Then run `vagrant destroy` to delete the broken VM. Then run `vagrant up`, which will download a VM which should have the `/vagrant` directory mounted.
