### ISSUE TITLE
Facebook OAuth setup instructions need updating

### ISSUE THREAD

**Issue by SteveWooding** [udacity/fsnd-issues#32]
In [this lesson](https://classroom.udacity.com/nanodegrees/nd004/parts/8d3e23e1-9ab6-47eb-b4f3-d5dc7ef27bf0/modules/348776022975461/lessons/3951228603/concepts/39497787740923), the Facebook OAuth setup instructions need updating. You could base the instructions on this [Stackoverflow answer](http://stackoverflow.com/a/37122933).

Thanks!

**Comment by veronikabenkeser** [comment]
Hi Steve! Thank you for bringing this to our attention and providing that Stackoverflow link! Just got it fixed :)
