### ISSUE TITLE
FSND-Virtual-Machine.zip needs updating

### ISSUE THREAD

**Issue by SteveWooding** [udacity/fsnd-issues#33]
Since most students download the zip file ([on this page](https://classroom.udacity.com/nanodegrees/nd004/parts/8d3e23e1-9ab6-47eb-b4f3-d5dc7ef27bf0/modules/bc51d967-cb21-46f4-90ea-caf73439dc59/lessons/5475ecd6-cfdb-4418-85a2-f2583074c08d/concepts/14c72fe3-e3fe-4959-9c4b-467cf5b7c3a0)), rather than cloning the repository, the latest critical update to the `Vagrantfile` needs to be reflected in the ZIP file download.

Thanks!

**Comment by karlud** [comment]
Done. Thank you!
