### ISSUE TITLE
Fix delete menu item HTML template

### ISSUE THREAD

**Issue by SteveWooding** [udacity/fsnd-issues#34]
In [this quiz](https://classroom.udacity.com/nanodegrees/nd004/parts/8d3e23e1-9ab6-47eb-b4f3-d5dc7ef27bf0/modules/348776022975460/lessons/3593308717/concepts/36245586280923), the delete menu item template does not work with the given solution.

I have [submitted a PR](https://github.com/lobrown/Full-Stack-Foundations/pull/86) to the repository on Lo Brown's account, but not sure if he still works at Udacity. Who as write access to this repo? You may need to fork this to the Udacity account, change all the links in the course, then maintain it from the Udacity account.

Thanks!

**Comment by karlud** [comment]
Merged, now that we own the repo. Thanks!
