### ISSUE TITLE
Missing link in instructor notes

### ISSUE THREAD

**Issue by SteveWooding** [udacity/fsnd-issues#36]
In [this video](https://classroom.udacity.com/nanodegrees/nd004/parts/135b6edc-f1cd-4cd9-b831-1908ede75737/modules/4fd8d440-9428-4de7-93c0-4dca17a36700/lessons/8307966915/concepts/83088569510923), the instructor mentions that there should be a link in the instructor notes to more information about the Maps API premium plan, but it's missing. The following link looks like a good suggestion (by HassenPy in the forums):

https://developers.google.com/maps/pricing-and-plans/

Thanks!

**Comment by karlud** [comment]
Added. Thanks!
