### ISSUE TITLE
Confusing Link

### ISSUE THREAD

**Issue by TAQ2** [udacity/fsnd-issues#39]
On the following page (Movie Trailer Website part 3). Point 4 has a link taking the user to the github repo, however, it directs to the main file of that repo. A student got confused by this because he was not familiar with github. In my opinion, this link is misleading - it should either take the user to the homepage of the repo or specify that it directs to the main file of the repo.

https://classroom.udacity.com/nanodegrees/nd004/parts/e5d3ef3d-fc60-4f4a-ba08-342e00e2bf92/modules/3a35570a-8e9d-4088-96d0-3dbe22d1fcb6/lessons/3561209451239847/concepts/36057486950923

**Comment by karlud** [comment]
I've implemented the suggested change. Thank you!
