### ISSUE TITLE
Typo in Sublime Text Setup in Windows Setup

### ISSUE THREAD

**Issue by SteveWooding** [udacity/fsnd-issues#4]
On [this page](https://classroom.udacity.com/nanodegrees/nd004/parts/f05dd1a8-5cb0-44ce-b9e9-b30fc274bcdc/modules/6b870a4f-94d1-4e8b-986c-0ace411d63e7/lessons/1b369991-f1ca-4d6a-ba8f-e8318d76322f/concepts/8a5af628-7a18-49cf-bbc8-02691762f862#), in the section "Sublime Text Setup", there is a missing single quote at the start of the file path. The command should be:

```
git config --global core.editor "'C:/Program Files/Sublime Text 2/sublime_text.exe' -n -w"
```

**Comment by forbiddenvoid** [comment]
Fixed
