### ISSUE TITLE
Missing link in fork lesson

### ISSUE THREAD

**Issue by SteveWooding** [udacity/fsnd-issues#40]
On [this page](https://classroom.udacity.com/nanodegrees/nd004/parts/f05dd1a8-5cb0-44ce-b9e9-b30fc274bcdc/modules/6b870a4f-94d1-4e8b-986c-0ace411d63e7/lessons/5e203cba-a6a7-4f9f-8a72-65ea05b1f74b/concepts/9462fdee-18d9-4e88-9442-85fcc5e42b69), in the section *Alter a Cloned Repo*, first checkbox, the text "Lam's my-travel-plans project" should be hyperlinked to https://github.com/udacity/course-collaboration-travel-plans, just as it does later on the page. But the very first time is important to avoid confusion.

Thanks!

**Comment by karlud** [comment]
Done.
