### ISSUE TITLE
Correction needed about Twilio

### ISSUE THREAD

**Issue by SteveWooding** [udacity/fsnd-issues#41]
On the video on [this page](https://classroom.udacity.com/nanodegrees/nd004/parts/fe2ad0cf-06b0-4541-87ab-0b6d59e21ef1/modules/356120945175460/lessons/991551862/concepts/10134987320923), the video mentions a now outdated module name for the Twilio client. It has changed from `TwilioRestClient` to just `Client`. This makes a lot of sense for that project. Much neater.

So maybe just a note below the video to flag up this change.

Thanks!

**Comment by karlud** [comment]
Fixed. Thanks!
