### ISSUE TITLE
Solution code given away in starter code

### ISSUE THREAD

**Issue by SteveWooding** [udacity/fsnd-issues#42]
The starter code [here](https://github.com/udacity/APIs/blob/master/Lesson_3/06_Adding%20Features%20to%20your%20Mashup/Starter%20Code/views.py) is the same as the solution code [here](https://github.com/udacity/APIs/blob/master/Lesson_3/06_Adding%20Features%20to%20your%20Mashup/Solution%20Code/views.py). 

In the video, the `restaurant_handler()` function is completely empty. Should this indeed be the case in the starter code?

**Comment by SteveWooding** [comment]
What does the label `course-replacement` mean?

**Comment by veronikabenkeser** [comment]
Hi Steve!

Thank you for bring this to our attention. That label means we'll be replacing the course, but we went ahead and fixed this bug. Happy Learning!
