### ISSUE TITLE
Improve Heroku deployment instructions

### ISSUE THREAD

**Issue by SteveWooding** [udacity/fsnd-issues#43]
In the section *Create configuration files* on [this page](https://classroom.udacity.com/nanodegrees/nd004/parts/f05dd1a8-5cb0-44ce-b9e9-b30fc274bcdc/modules/b08bb93f-d13e-42d6-a60c-8c7d4d263c42/lessons/773150bb-8e88-4457-b077-3b8a02018f33/concepts/1d84f620-4d25-45fd-aa10-276498e328ae), maybe make it more clear to students that they have to add and commit the configuration files to the repository. I came across a student who missed this required step.

Thanks!

**Comment by karlud** [comment]
Added. Thanks!
