### ISSUE TITLE
Slight modification in Instructions for Logs Analysis Project

### ISSUE THREAD

**Issue by ravikumarseth** [udacity/fsnd-issues#44]
In the setup instructions for Logs Analysis Project, it would be easier to follow for students if the instructions asked to cd in to the vagrant directory on the Linux by running `cd /vagrant` before running `psql -d news -f newsdata.sql`. Students follow all steps finally finding them struck here.

Link to the description page: https://classroom.udacity.com/nanodegrees/nd004/parts/8d3e23e1-9ab6-47eb-b4f3-d5dc7ef27bf0/modules/bc51d967-cb21-46f4-90ea-caf73439dc59/lessons/262a84d7-86dc-487d-98f9-648aa7ca5a0f/concepts/a9cf98c8-0325-4c68-b972-58d5957f1a91

**Comment by forbiddenvoid** [comment]
Updated.
