### ISSUE TITLE
Add note about Python 3 version of Apache WSGI module

### ISSUE THREAD

**Issue by SteveWooding** [udacity/fsnd-issues#45]
Some students are built their Item Catalog app with Python 3 (which is great). However, when it comes to the last project and deploying the app, they need to install the Ubuntu package `libapache2-mod-wsgi-py3` instead of the Python 2 version.

A note could be added to the [Project Details](https://classroom.udacity.com/nanodegrees/nd004/parts/ab002e9a-b26c-43a4-8460-dc4c4b11c379/modules/357367901175462/lessons/3573679011239847/concepts/ce268cfe-99ec-49be-9326-876375f89a22) page about this.

**Comment by forbiddenvoid** [comment]
Noted.
