### ISSUE TITLE
Wrong answer for Git course quiz.

### ISSUE THREAD

**Issue by ravikumarseth** [udacity/fsnd-issues#47]
Quiz 2 of 2: The quiz marks wrong answer as correct.

The quiz accepts
```
On branch master
Initial Commit
nothing to commit (create/copy files and use "git add" to track)
```
as answer, when no initial commit has been made.

Link: https://classroom.udacity.com/courses/ud123/lessons/437a88fc-15f5-48b8-a6a5-0cf3347e6183/concepts/ce648229-7d6c-4ad3-805e-af6a77f38fd0

**Comment by ravikumarseth** [comment]
I have recently noticed that the new git version shows
```
$ git status

On branch master
No commits yet
nothing to commit (create/copy files and use "git add" to track)
```
This means that a lot of content will need to be updated.
Content changes needs to be made [here](https://classroom.udacity.com/courses/ud123/lessons/5f584ce7-1b7b-4848-80c1-b559739ea363/concepts/85cd2f5e-a3a9-467f-9043-96d8b627787b) and [here](https://classroom.udacity.com/courses/ud123/lessons/437a88fc-15f5-48b8-a6a5-0cf3347e6183/concepts/ce648229-7d6c-4ad3-805e-af6a77f38fd0)

**Comment by richardkalehoff** [comment]
This is fantastic, and thank you _so_ much for the Udacity Classroom links that needed updating! :raised_hands: I've updated the quiz and added a notice to the classroom about how the `git status` command has changed in version 2.14 :+1:
