### ISSUE TITLE
Corrupt zip file

### ISSUE THREAD

**Issue by SteveWooding** [udacity/fsnd-issues#48]
The file `static.zip` in the supporting materials section of [this page](https://classroom.udacity.com/nanodegrees/nd004/parts/8d3e23e1-9ab6-47eb-b4f3-d5dc7ef27bf0/modules/348776022975460/lessons/3593308717/concepts/36197688140923) seems to be corrupt. A student and myself could not extract the files from it (only list the files).

So this needs to be re-mastered.

Thanks!

**Comment by karlud** [comment]
It sure is. I wonder how that happened.

$ unzip static.zip
Archive:  static.zip
warning [static.zip]:  5 extra bytes at beginning or within zipfile
  (attempting to process anyway)
file #1:  bad zipfile offset (local header sig):  5
  (attempting to re-compensate)
   creating: static/
  inflating: static/.DS_Store
   creating: __MACOSX/
   creating: __MACOSX/static/
  inflating: __MACOSX/static/._.DS_Store
  inflating: static/background.jpg
  inflating: __MACOSX/static/._background.jpg
  inflating: static/img3.jpg
  error:  invalid compressed data to inflate
file #9:  bad zipfile offset (local header sig):  5146574
  (attempting to re-compensate)
  inflating: __MACOSX/static/._img3.jpg
  inflating: static/styles.css

**Comment by karlud** [comment]
Of the two jpegs in this file, one of them is corrupted in the zipfile and the other is not actually used in the project. I'm just gonna remove them.

**Comment by karlud** [comment]
Done. The new zipfile just contains the CSS, which is all that's actually used in the video. I've also moved static.zip and templates.zip to our new static file hosting service instead of the ancient one that they were on.
