### ISSUE TITLE
Missing step in Flask lessons

### ISSUE THREAD

**Issue by SteveWooding** [udacity/fsnd-issues#49]
Could add a note under [this video](https://classroom.udacity.com/nanodegrees/nd004/parts/8d3e23e1-9ab6-47eb-b4f3-d5dc7ef27bf0/modules/348776022975460/lessons/3593308717/concepts/36245586240923), about adding a link to create a new menu item on the `menu.html` page. On the previous page, the student is asked to add the edit and delete links, but not the new menu links. So this is then missing from the student's working copy of the code.

Thanks!

**Comment by forbiddenvoid** [comment]
Great catch. I've added a note to the video with instructions for adding that step of the process.
