### ISSUE TITLE
Add requests package back into FSND VM

### ISSUE THREAD

**Issue by SteveWooding** [udacity/fsnd-issues#5]
In the previous version of the FSND VM, when we had the `pg_config.sh`, the `requests` package was installed (required for GConnect lesson). Since no other package requires this package, in the current version of FSND VM, it never gets installed. So it needs to be added to the `Vagrantfile`. I will publish a pull request to due course to implement this.

**Comment by SteveWooding** [comment]
Created this pull request to add back the installation of the `requests` package: https://github.com/udacity/fullstack-nanodegree-vm/pull/70

**Comment by forbiddenvoid** [comment]
merged
