### ISSUE TITLE
Relative Neighbors

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fsnd-issues#50]
https://classroom.udacity.com/nanodegrees/nd004/parts/fe2ad0cf-06b0-4541-87ab-0b6d59e21ef1/modules/31cc93f7-9d62-44d2-b0fc-ab68b4ff90f0/lessons/5bc1143d-6294-412b-9a32-27d17142f9d2/concepts/dfdd39e3-09c1-4fe9-b7b5-cdf0a2d8b0db

Info from student:
Example website: http://udacity.github.io/fend/fend-refresh/lesson6/relative-flow/animation.html 
It says: 
Also, notice how the blue box finishes **on top of** the purple box. Overlapping siblings necessarily appear on top of or behind one another (you can't mix elements like you would mix paint!). What happens when elements overlap depends on their order in the DOM. The earlier an element appears in the DOM, the "higher" the element is. As the blue element was laid down before the purple element, it is treated as higher so it displays on top.

but in the article (url was given in the next lesson 10. 3D websites): https://philipwalton.com/articles/what-no-one-told-you-about-z-index/ 
It says: 
When you introduce the position property into the mix, any positioned elements (and their children) are displayed in front of any non-positioned elements. (To say an element is “positioned” means that it has a position value other than static, e.g., relative, absolute, etc.)

I believe this is the actual reason and not "What happens when elements overlap depends on their order in the DOM. The **earlier** an element appears in the DOM, the "higher" the element is.", and after experience I found out that this was not the case.

1. The video explains my question: https://youtu.be/t_3pjXk5dyM 
2. The png file attached is to make the matter more clearly, since I was stacking only horizontally in the video.

**Comment by richardkalehoff** [comment]
The student is correct (and provided a _fantastic_ ticket that included a video! :heart_eyes:). I have re-worded the page to correct the confusing/incorrect wording.
