### ISSUE TITLE
Missing Files Pale Kale Test

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fsnd-issues#51]
https://classroom.udacity.com/nanodegrees/nd004/parts/8d3e23e1-9ab6-47eb-b4f3-d5dc7ef27bf0/modules/47a1ea0f-75ff-4654-9c90-89cf02246783/lessons/4592928861/concepts/52457425980923

The starter code under the video is missing.

**Comment by forbiddenvoid** [comment]
The starter code is under the video in a link to a GitHub repo.
