### ISSUE TITLE
Typo: Project>Build a Portfolio Site>Rubric

### ISSUE THREAD

**Issue by candy02058912** [udacity/fsnd-issues#52]
Link: https://review.udacity.com/#!/rubrics/45/view

> If you're using `Bootstrap` or standard `HMTL/CSS`: the rows and columns of the grid must be wrapped in an element with a `container` class.

HMTL => HTML

Just wondering if this is the actual place to report a typo, hope it doesn't cause too much trouble, just want the course to get better and better with less errors 👍 since it really has been helping me lots!

**Comment by forbiddenvoid** [comment]
Good catch! Fixed!
