### ISSUE TITLE
No.15 Quiz: Message Flashing

### ISSUE THREAD

**Issue by arrickx** [udacity/fsnd-issues#53]
https://github.com/udacity/Full-Stack-Foundations/blob/master/Lesson-3/16_Flash-Messaging/menu.html

<a href = "{{url_for('newMenuItem', restaurant_id=restaurant.id)}}">Create New Item</a>  this is missing. so after you create a new item. you can not create another anymore.

**Comment by forbiddenvoid** [comment]
The code is an example (it doesn't contain the complete code for the in-class project). It's not important for that link to be in that HTML file.
