### ISSUE TITLE
Required user not in usersWithTokens.db

### ISSUE THREAD

**Issue by SteveWooding** [udacity/fsnd-issues#54]
The file [here](https://github.com/udacity/APIs/tree/master/Lesson_4/07_Implementing%20Token-Based%20Authentication%20in%20Flask) does not contain the `Lorenzo:Udacity` user required to make the code in [this video](https://classroom.udacity.com/nanodegrees/nd004/parts/8d3e23e1-9ab6-47eb-b4f3-d5dc7ef27bf0/modules/47a1ea0f-75ff-4654-9c90-89cf02246783/lessons/4592928861/concepts/52457425920923) work correctly.

Students need to re-run the user registration step in order to add that user to the SQLite file. Recommend updating this file so that is not required.

**Comment by forbiddenvoid** [comment]
Probably not going to fix this. It's low priority and low impact, so it probably won't get updated before this course is replaced/updated.
