### ISSUE TITLE
Repeat link to course-ud303 repository

### ISSUE THREAD

**Issue by SteveWooding** [udacity/fsnd-issues#55]
On [this page](https://classroom.udacity.com/nanodegrees/nd004/parts/f05dd1a8-5cb0-44ce-b9e9-b30fc274bcdc/modules/b08bb93f-d13e-42d6-a60c-8c7d4d263c42/lessons/e666fd9d-84e8-4e06-a5f7-bd3ea26a1693/concepts/e4a49aed-7377-4cda-9cba-e951cf9842f9), it might be good to include a link directly to the ud303 course GitHub repository here, rather than referring to the previous lesson (has caused some confusion).

Thanks!

**Comment by forbiddenvoid** [comment]
Updated.
