### ISSUE TITLE
Fixed Flow Quiz

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fsnd-issues#56]
https://classroom.udacity.com/nanodegrees/nd004/parts/fe2ad0cf-06b0-4541-87ab-0b6d59e21ef1

Fixed Flow Quiz

Says "Try Again", but also says "All items were correct!"

Zendesk Ticket #579869

**Comment by karlud** [comment]
The URL in this bug does not point to a quiz. What quiz is being referred to here?

**Comment by JessicaBettencourt** [comment]
https://classroom.udacity.com/nanodegrees/nd004/parts/fe2ad0cf-06b0-4541-87ab-0b6d59e21ef1/modules/31cc93f7-9d62-44d2-b0fc-ab68b4ff90f0/lessons/5bc1143d-6294-412b-9a32-27d17142f9d2/concepts/1d3fe7e3-ea1d-4815-8120-664365746a30#

Sorry, wrong link. Fixed Flow Quiz in Programming Fundamentals and the Web

**Comment by karlud** [comment]
This is a frontend feedback extension based quiz. These will be replaced by the new HTML/CSS material.
