### ISSUE TITLE
Broken Link Your First Web Server

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fsnd-issues#57]
https://classroom.udacity.com/nanodegrees/nd004/parts/f05dd1a8-5cb0-44ce-b9e9-b30fc274bcdc/modules/b08bb93f-d13e-42d6-a60c-8c7d4d263c42/lessons/6ff26dd7-51d6-49b3-9f90-41377bff4564/concepts/23abdb2d-fbd3-4b40-b190-c8e6b7feaa29

Lesson 11: Requests & Responses

2. Your First Web Server

Broken Link: http://localhost:8000/

Version 4

Ticket #575117

**Comment by karlud** [comment]
This link isn't broken if the student has got a web server up and running on that port.

**Comment by hbkwong** [comment]
Hey @JessicaBettencourt, just tested this and I got the expected result that the link describes. Did the student have other details to reproduce the error?

**Comment by JessicaBettencourt** [comment]
I have another student writing in with a similar  issue:

I am unable to access "http://localhost:8000". I have all the required programs installed: 
- Python3.x (and Python 2.x), 
- Git version 2.14.1.windows1, 
- Nmap 
When using Git to start the process, I receive this error: after this command "python -m http.server 8000" & "python3 -m http.server 8000" : "bash: python3.5: command not found" or "C:\Python27\python.exe: No module named http". 

Is there something they might be doing wrong?

**Comment by karlud** [comment]
On Mon, Oct 2, 2017 at 11:37 AM, JessicaBettencourt <
notifications@github.com> wrote:

> I have another student writing in with a similar issue:
>
> I am unable to access "http://localhost:8000". I have all the required
> programs installed:
>
>    - Python3.x (and Python 2.x),
>    - Git version 2.14.1.windows1,
>    - Nmap
>    When using Git to start the process, I receive this error: after this
>    command "python -m http.server 8000" & "python3 -m http.server 8000" :
>    "bash: python3.5: command not found" or "C:\Python27\python.exe: No module
>    named http".
>
> Is there something they might be doing wrong?
>
This sounds to me as if the student does not have Python 3 installed
correctly.

If the student has Python 3 installed, it will be installed with either the
command name *python3*, or the command name *python*. They can use this
command name with the *--version* option to check. This is one of the
instructions on the first page ("Introduction") of the HTTP & Web Servers
course:

https://classroom.udacity.com/nanodegrees/nd004/parts/f05dd1a8-5cb0-44ce-b9e9-b30fc274bcdc/modules/b08bb93f-d13e-42d6-a60c-8c7d4d263c42/lessons/6ff26dd7-51d6-49b3-9f90-41377bff4564/concepts/ab2f6d8d-fef4-4997-9768-e6e73325b9cb?contentVersion=4.0.0&contentLocale=en-us

They should try running the command *python --version* and see if that
prints out a Python 3 version message. If it doesn't, they should try *python3
--version*. Whichever Python command name gives them Python 3, that's the
one they should use throughout this course.

If they continue to get a "command not found" or "Python27" message, they
need to (re)install Python 3.

-k.

**Comment by JessicaBettencourt** [comment]
Thank you so much Karl!
