### ISSUE TITLE
Hostnames and ports

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fsnd-issues#58]
https://classroom.udacity.com/nanodegrees/nd004/parts/f05dd1a8-5cb0-44ce-b9e9-b30fc274bcdc/modules/b08bb93f-d13e-42d6-a60c-8c7d4d263c42/lessons/6ff26dd7-51d6-49b3-9f90-41377bff4564/concepts/34ad0283-c360-443a-a18a-dbbbce982db0

Lesson 11: Requests and Responses 
4. Hostnames and ports

Question 2 of 3-  needs rewording 

version 4.0

Ticket #580590

**Comment by karlud** [comment]
What needs rewording about it?

**Comment by JessicaBettencourt** [comment]
Question is "Use the host or nslookup command to find the IPv4 addresses of en.wikipedia.org and ja.wikipedia.org — the servers for Wikipedia in English and Japanese. Are these sites on the same IP address?"

It looks like it could be yes OR no, which isn't ideal.

**Comment by karlud** [comment]
I have changed this quiz to accept any answer, with a note that WMF (the Wikipedia people) might move their servers around.
