### ISSUE TITLE
Planning a Secret Message- Link issue

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fsnd-issues#59]
https://classroom.udacity.com/nanodegrees/nd004/parts/fe2ad0cf-06b0-4541-87ab-0b6d59e21ef1/modules/356120945175460/lessons/993460168/concepts/9977893180923

The forum thread the link leads to is full. Can we either replace it with https://discussions.udacity.com/t/planning-a-secret-messge/42081/1083 or take out this sentence prompting them to post on this thread?

Ticket #582747

**Comment by karlud** [comment]
Done.
