### ISSUE TITLE
Image versus website confusion

### ISSUE THREAD

**Issue by SteveWooding** [udacity/fsnd-issues#60]
On the page [Relative Flow Quiz](https://classroom.udacity.com/nanodegrees/nd004/parts/fe2ad0cf-06b0-4541-87ab-0b6d59e21ef1/modules/31cc93f7-9d62-44d2-b0fc-ab68b4ff90f0/lessons/5bc1143d-6294-412b-9a32-27d17142f9d2/concepts/46f2fe6f-e4ce-44c1-bf98-8a3ca0c55e1e), it is not clear that the website mentioned is not supposed to look like the image on the page. A student thought there was something wrong with the rendering of the website.

I seem to remember that previously, students were tasked with changing the website CSS so it looks like the image. This seems to have gone. Maybe a slight change to the wording on the page might be useful to clarify things.

**Comment by karlud** [comment]
Added a note: "This is what the site should look like before you edit it."
