### ISSUE TITLE
Update Title of File- Git Key Terms

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fsnd-issues#62]
https://classroom.udacity.com/nanodegrees/nd004/parts/f05dd1a8-5cb0-44ce-b9e9-b30fc274bcdc/modules/6b870a4f-94d1-4e8b-986c-0ace411d63e7/lessons/1b369991-f1ca-4d6a-ba8f-e8318d76322f/concepts/5f703930-a95e-47f0-a56b-702ed3a93741

The page states to find this file: You can find the Terminology handout in the Resources panel. The file is named Git Terms PDF and is in the Course Materials section. There isn't one named Git Terms PDF. It is labeled Git Key Terms.

Ticket #: 584707

**Comment by karlud** [comment]
Fixed!
