### ISSUE TITLE
Slight page formatting issue

### ISSUE THREAD

**Issue by SteveWooding** [udacity/fsnd-issues#63]
On [this page](https://classroom.udacity.com/nanodegrees/nd004/parts/ab002e9a-b26c-43a4-8460-dc4c4b11c379/modules/357367901175462/lessons/3573679011239847/concepts/ce268cfe-99ec-49be-9326-876375f89a22), point 11 needs to go on a new line. It is currently at the end of the previous bullet point.

See image below...

![image](https://user-images.githubusercontent.com/7372191/31120429-44893eae-a82c-11e7-97bc-b1553222dfd9.png)

**Comment by forbiddenvoid** [comment]
Fixed.
