### ISSUE TITLE
Stay in Sync with Source Project: Git Fetch

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fsnd-issues#64]
https://classroom.udacity.com/nanodegrees/nd004/parts/f05dd1a8-5cb0-44ce-b9e9-b30fc274bcdc/modules/6b870a4f-94d1-4e8b-986c-0ace411d63e7/lessons/e295524f-87b6-4981-af74-6b20231dc7c1/concepts/48825e17-72c6-4c3e-9c98-1add66bf1c86

Info from student:

Section is:
Pulling Upstream Changes

Command is:
$ git pull upstream master 
The caption says:
The terminal application showing the results of doing git fetch upstream master. A new branch is added to the local repository.
Git pull, git fetch.

I think the command should be git fetch, not git pull.

Ticket #:586048

**Comment by karlud** [comment]
Fixed!

**Comment by JessicaBettencourt** [comment]
Thank you!
