### ISSUE TITLE
Confusing quiz feedback

### ISSUE THREAD

**Issue by SteveWooding** [udacity/fsnd-issues#65]
For [this quiz](https://classroom.udacity.com/nanodegrees/nd004/parts/fe2ad0cf-06b0-4541-87ab-0b6d59e21ef1/modules/31cc93f7-9d62-44d2-b0fc-ab68b4ff90f0/lessons/6058dc09-0ca3-4734-89a9-4f7739c26a47/concepts/73229895910923), the feedback when an incorrect answer is given has a line about going on to the next quiz, whereas the success feedback hasn't got this line. It would make more sense to move it to the success feedback message.

**Comment by karlud** [comment]
Updated. Thanks!
