### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by candy02058912** [udacity/fsnd-issues#67]
Location: 2. Developers' Tools > The Web from Python > 5. HTML and forms

> If you need a refresher on HTML forms, take a look at the **MDN introduction (gentle)** or the W3C standard reference (more advanced).

The MDN introduction points to: https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Forms_in_HTML which shows a not found.

**Comment by karlud** [comment]
Fixed: https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms
