### ISSUE TITLE
Git Diff - add line, no need to commit

### ISSUE THREAD

**Issue by SteveWooding** [udacity/fsnd-issues#68]
In the [Git Diff](https://classroom.udacity.com/nanodegrees/nd004/parts/f05dd1a8-5cb0-44ce-b9e9-b30fc274bcdc/modules/6b870a4f-94d1-4e8b-986c-0ace411d63e7/lessons/5f584ce7-1b7b-4848-80c1-b559739ea363/concepts/60adab01-79c2-4bed-8ffc-384ad22a9e30) part, the course talks about changing the `index.html` file and running `git diff`. A note is needed to say that this change need not be committed and to revert the file to how it was. A student got confused when later on in the course, no mention of this change was in the git log.

**Comment by richardkalehoff** [comment]
I've added a section informing students that the changes were for demo purposes only and were not committed to the repo.
