### ISSUE TITLE
Add instruction to create project.docx file

### ISSUE THREAD

**Issue by SteveWooding** [udacity/fsnd-issues#69]
On the page [Having Git Ignore Files](https://classroom.udacity.com/nanodegrees/nd004/parts/f05dd1a8-5cb0-44ce-b9e9-b30fc274bcdc/modules/6b870a4f-94d1-4e8b-986c-0ace411d63e7/lessons/5f584ce7-1b7b-4848-80c1-b559739ea363/concepts/d4275710-06eb-431c-bec6-13a202f1dfbb), a student was puzzled as to where the file `project.docx` came from. Maybe add an instruction to the page to create this file with the command `touch project.docx`. Thanks.

**Comment by richardkalehoff** [comment]
I've changed the text to include `touch project.docx` so that students can follow along. Thanks for the feedback!
