### ISSUE TITLE
Quiz not accepting correct answer

### ISSUE THREAD

**Issue by SteveWooding** [udacity/fsnd-issues#7]
The quiz on the page [Debugging CSS Part 1](https://classroom.udacity.com/nanodegrees/nd004/parts/fe2ad0cf-06b0-4541-87ab-0b6d59e21ef1/modules/31cc93f7-9d62-44d2-b0fc-ab68b4ff90f0/lessons/5bc1143d-6294-412b-9a32-27d17142f9d2/concepts/d5f04128-9826-43f9-8bf3-240c7001b6f1) is not working when any answer is entered.

Checking the developer console, there is a TypeError: `Cannot read property 'node_key' of undefined` and then a gateway time out a little while afterwards.

**Comment by SteveWooding** [comment]
Another student has reported this today. Would be great to get this fixed soon. Thanks!

**Comment by forbiddenvoid** [comment]
This was already fixed.
