### ISSUE TITLE
Clearfix Quiz - possible incorrect answer

### ISSUE THREAD

**Issue by SteveWooding** [udacity/fsnd-issues#72]
[This quiz](https://classroom.udacity.com/nanodegrees/nd004/parts/fe2ad0cf-06b0-4541-87ab-0b6d59e21ef1/modules/31cc93f7-9d62-44d2-b0fc-ab68b4ff90f0/lessons/171900e0-d0ab-465b-b747-402a3adcffc5/concepts/90f3db8f-f3fa-4dce-b7fb-4a2ece9c53d5#) says that option 2 is not correct. However, several students and I have tested this on both Chrome and Firefox, and a horizontal scrollbar is added when reducing the width of the `.row` parent class.

So it looks like the quiz should accept option 1 and 2 as correct responses. Thanks!

**Comment by forbiddenvoid** [comment]
I deleted that answer as an option. The issue is that horizontal scrollbar is unrelated to the overflow attribute. It's created whether overflow is set to auto or not.
