### ISSUE TITLE
HTML Structure Part 2- this clip link

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fsnd-issues#74]
https://classroom.udacity.com/nanodegrees/nd004/parts/fe2ad0cf-06b0-4541-87ab-0b6d59e21ef1/modules/31cc93f7-9d62-44d2-b0fc-ab68b4ff90f0/lessons/6058dc09-0ca3-4734-89a9-4f7739c26a47/concepts/4a788a8e-2d58-4ba3-9469-c1728c410dea

Remember "this clip" from the beginning of the lesson?

^^"this clip" takes them to a lesson that they do not have permission to access

Ticket #601172

**Comment by karlud** [comment]
Fixed by changing to a relative URL. Thanks for noticing!
