### ISSUE TITLE
Add note about ISPs returning 200 for bad domains

### ISSUE THREAD

**Issue by SteveWooding** [udacity/fsnd-issues#75]
In quiz 3 on page [Making requests](https://classroom.udacity.com/nanodegrees/nd004/parts/f05dd1a8-5cb0-44ce-b9e9-b30fc274bcdc/modules/b08bb93f-d13e-42d6-a60c-8c7d4d263c42/lessons/e666fd9d-84e8-4e06-a5f7-bd3ea26a1693/concepts/e212b78b-584b-4425-ad96-3a3270a4727b), if the student's ISP redirects to a custom error page, then a 200 will be returned.

See [this post](https://discussions.udacity.com/t/lesson-12-the-web-from-python-quiz/404553) on the forums for an example.

Could add a note about this situation.

**Comment by karlud** [comment]
This is such bad behavior for ISPs. But yeah, some do it. I'll add a mention of it to the quiz feedback.
