### ISSUE TITLE
Add missing step to Vagrant VM instructions

### ISSUE THREAD

**Issue by SteveWooding** [udacity/fsnd-issues#76]
In the Vagrant VM instructions on [this page](https://classroom.udacity.com/nanodegrees/nd004/parts/8d3e23e1-9ab6-47eb-b4f3-d5dc7ef27bf0/modules/348776022975460/lessons/3621198668/concepts/35960790720923), under the heading "Run the virtual machine!", there is a missing step in the directions.

They should also say to change directory to `fullstack/vagrant`, as this is where the `Vagrantfile` is located.

Thanks.

**Comment by karlud** [comment]
Yep, Fixed.
