### ISSUE TITLE
VM instructions

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fsnd-issues#78]
https://classroom.udacity.com/nanodegrees/nd004/parts/8d3e23e1-9ab6-47eb-b4f3-d5dc7ef27bf0/modules/348776022975460/lessons/3621198668/concepts/35960790720923

On this page [1] the instructions in the section "Run the virtual machine!" are missing the step “cd vagrant” after “cd fullstack”. Without this step, the virtual machine is not launched correctly.

Ticket #604504

**Comment by karlud** [comment]
Yep! Fixed.
