### ISSUE TITLE
Part of CSS header quiz broken

### ISSUE THREAD

**Issue by SteveWooding** [udacity/fsnd-issues#79]
The quiz on [this page](https://classroom.udacity.com/nanodegrees/nd004/parts/fe2ad0cf-06b0-4541-87ab-0b6d59e21ef1/modules/31cc93f7-9d62-44d2-b0fc-ab68b4ff90f0/lessons/b8bf7408-6bd8-499e-b3f2-e6843788f2fb/concepts/75570469630923) does not mark as correct the header font-weight CSS property. I tried several values, including 400 and "normal" (as this was in the JSON tests file), but nothing worked.

All other tests in the quiz work OK.

**Comment by forbiddenvoid** [comment]
This was resolved! We've removed the Chrome Extension. This work is now done in workspaces.
