### ISSUE TITLE
Link to Vagrant installation instructions incorrect

### ISSUE THREAD

**Issue by SteveWooding** [udacity/fsnd-issues#8]
On [this page](https://classroom.udacity.com/nanodegrees/nd004/parts/8d3e23e1-9ab6-47eb-b4f3-d5dc7ef27bf0/modules/bc51d967-cb21-46f4-90ea-caf73439dc59/lessons/262a84d7-86dc-487d-98f9-648aa7ca5a0f/concepts/a9cf98c8-0325-4c68-b972-58d5957f1a91), heading *Getting an error?*, the link here goes to the wrong page. Should at least go to [this page](https://classroom.udacity.com/nanodegrees/nd004/parts/8d3e23e1-9ab6-47eb-b4f3-d5dc7ef27bf0/modules/bc51d967-cb21-46f4-90ea-caf73439dc59/lessons/5475ecd6-cfdb-4418-85a2-f2583074c08d/concepts/14c72fe3-e3fe-4959-9c4b-467cf5b7c3a0) or be a link to the FSND VM zip file itself.

**Comment by karlud** [comment]
Fixed.
