### ISSUE TITLE
Link to learn more about grids out of date

### ISSUE THREAD

**Issue by SteveWooding** [udacity/fsnd-issues#81]
The link on [this page](https://classroom.udacity.com/nanodegrees/nd004/parts/fe2ad0cf-06b0-4541-87ab-0b6d59e21ef1/modules/afa5ca8b-f8dc-4160-83ff-3e5ccc2e1972/lessons/e4b4d168-03d7-4d93-b7fb-a6dc1c62a25b/concepts/36189685380923#) seems to be out of date, as the course "Intro to HTML and CSS" does not contain hardly any content about grids.

Maybe a better resource to link to would be the MDN basic guide to grids [here](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Basic_Concepts_of_Grid_Layout)

**Comment by karlud** [comment]
Great choice. Done!
