### ISSUE TITLE
Unexpected behaviour on Windows 10 when two processes use the same port

### ISSUE THREAD

**Issue by SteveWooding** [udacity/fsnd-issues#84]
In the 3rd question on the page [The echo server](https://classroom.udacity.com/nanodegrees/nd004/parts/f05dd1a8-5cb0-44ce-b9e9-b30fc274bcdc/modules/b08bb93f-d13e-42d6-a60c-8c7d4d263c42/lessons/e666fd9d-84e8-4e06-a5f7-bd3ea26a1693/concepts/b7f7c844-5027-4cc4-8ad8-0b2b87a35d63), on Windows 10 now, no `OSError` exception is raised.

The observed behaviour is that the second process waits patiently for the port to become available, without producing an error. If you then stop the first process, the second process grabs the port and starts to work as expected.

So a note regarding this will need to be added for Windows 10 users. Another example of Microsoft not following the accepted standards it seems.

**Comment by SteveWooding** [comment]
Had to explain this issue again today. A note in the course would be very useful.

**Comment by karlud** [comment]
Adding a note here. Thanks!
