### ISSUE TITLE
Inconsistent variable naming

### ISSUE THREAD

**Issue by SteveWooding** [udacity/fsnd-issues#85]
This [this file](https://github.com/udacity/Full-Stack-Foundations/blob/master/Lesson-3/12_Edit-Menu-Form/project.py), the naming style of the menu id is not the same as the rest of course code, which can confuse.

I have fixed this issue and added a missing import in this [pull request](https://github.com/udacity/Full-Stack-Foundations/pull/96).

**Comment by karlud** [comment]
Merged. Thanks!
