### ISSUE TITLE
Request for link to Medium website

### ISSUE THREAD

**Issue by SteveWooding** [udacity/fsnd-issues#86]
On the page [Number of Breakpoints](https://classroom.udacity.com/nanodegrees/nd004/parts/fe2ad0cf-06b0-4541-87ab-0b6d59e21ef1/modules/afa5ca8b-f8dc-4160-83ff-3e5ccc2e1972/lessons/e4b4d168-03d7-4d93-b7fb-a6dc1c62a25b/concepts/35690589170923), there is no link to the Medium website. A student requested this, and I am putting it forward here for consideration.

Thanks.

**Comment by karlud** [comment]
Yeah, the layout of medium.com has changed since this course was created. I'm adding a note about that. To get the correct answer on the quiz, students should look at how it behaves in the video.
