### ISSUE TITLE
Proposed addition to Vagrant troubleshooting section

### ISSUE THREAD

**Issue by SteveWooding** [udacity/fsnd-issues#9]
On the [Installing the Virtual Machine](https://classroom.udacity.com/nanodegrees/nd004/parts/8d3e23e1-9ab6-47eb-b4f3-d5dc7ef27bf0/modules/bc51d967-cb21-46f4-90ea-caf73439dc59/lessons/5475ecd6-cfdb-4418-85a2-f2583074c08d/concepts/14c72fe3-e3fe-4959-9c4b-467cf5b7c3a0) page, **Troubleshooting** section, consider recommending trying Vagrant 1.9.2, instead of the latest version.

Every version of Vagrant since 1.9.2 has at least one bug in it that some people run in to. Also note that on Ubuntu 17.04, they are still on Vagrant 1.9.1 (which is probably why I never have any issues). The latest is not always the greatest.

**Comment by karlud** [comment]
Added. Thanks for the suggestion.
