### ISSUE TITLE
Add step Google OAuth Step 1 instructions

### ISSUE THREAD

**Issue by SteveWooding** [udacity/fsnd-issues#90]
On [this page](https://classroom.udacity.com/nanodegrees/nd004/parts/8d3e23e1-9ab6-47eb-b4f3-d5dc7ef27bf0/modules/348776022975461/lessons/3967218625/concepts/39636486130923), it might be useful to add a step to download the JSON file from the Google developer's console.

**Comment by karlud** [comment]
Added a note that the student can do this.
