### ISSUE TITLE
Outdated video reference

### ISSUE THREAD

**Issue by forbiddenvoid** [udacity/fsnd-issues#92]

**Comment by forbiddenvoid** [comment]
In FSND Part 1, Lesson 19, Section 15, the video instructs us to visit another (free) course to learn more about the CSS grid system. However, the course that shows up from the link, while concerning HTML and CSS, does not have anything about grids. It is just some of the lessons that we already completed in the FSND (and IPND), and doesn't say anything about grids. There are some passing mentions of flexbox, which is covered in FSND 1.19.16 and further on.

**Comment by karlud** [comment]
Link?

**Comment by karlud** [comment]
I fixed this a while back; it's now a link to MDN.
