### ISSUE TITLE
Cancel buttons in restaurant code still submit the form

### ISSUE THREAD

**Issue by SteveWooding** [udacity/fsnd-issues#93]
On the delete and edit pages, when the cancel button is pressed the form is still submitted. This is because the default type of the button tag is "submit". For the cancel button, the type should be set to "button" instead. Then the form will no longer be submitted.

I have submitted the following pull request to fix this issue: https://github.com/udacity/ud330/pull/60

**Comment by karlud** [comment]
Merged. Thanks!
