### ISSUE TITLE
Google logout issue in final code

### ISSUE THREAD

**Issue by SteveWooding** [udacity/fsnd-issues#94]
In the final code example of the OAuth code (ud330/Lesson4/step2), logging out of a Google session fails, as there are duplicated deletions from the `login_session` dictionary.

To fix this issue, I have submitted a pull request that removes the deletions from the `gdisconnect()` function. This matches what happens in the Facebook disconnect function.

Here is a link to the pull request for your consideration: https://github.com/udacity/ud330/pull/61

**Comment by karlud** [comment]
Merged. Thanks!
