### ISSUE TITLE
Closing DB connection after returning from function

### ISSUE THREAD

**Issue by jaikathuria** [udacity/fsnd-issues#95]
Lesson 3: Python DB-API - 8. Give That App a Backend

```
def get_posts():
    db = psycopg2.connect("dbname = forum")
    c = db.cursor()
    c.execute("# some query ")
    return c.fetchall()
    db.close()
```

The database connection close statement is written after the return statement, which is confusing a lot of students.

**Comment by karlud** [comment]
Good catch. I've added an erratum about this.
