### ISSUE TITLE
Add note to re-sun lots of menus script in routing lesson

### ISSUE THREAD

**Issue by SteveWooding** [udacity/fsnd-issues#96]
The state of the database when the student arrives at the [Routing](https://classroom.udacity.com/nanodegrees/nd004/parts/8d3e23e1-9ab6-47eb-b4f3-d5dc7ef27bf0/modules/348776022975460/lessons/3593308717/concepts/36245586130923) lesson means that code will fail. A note to delete the database and rerun the `lotsofmenus.py` program to get a good state might be a good idea.

The issue is that the restaurant with an id of 1 is deleted in a previous lesson. Now in this lesson, it tries to access it.

**Comment by forbiddenvoid** [comment]
Added.
