### ISSUE TITLE
Link to Full Forum Thread

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fsnd-issues#98]
https://classroom.udacity.com/nanodegrees/nd004-intr1/parts/4755cfe6-bd20-46a8-afc9-4c513d17d72f/modules/d90b5403-5806-4b02-8573-37d102148d83/lessons/993460168/concepts/9977893240923#

The "Rename Troubles" thread is full. It can be replaced with this one: https://discussions.udacity.com/t/rename-troubles/123001

**Comment by karlud** [comment]
Fixed. Thanks!
